### ISSUE TITLE
4-Wrong Website Name: 10/25/50 in main canvas

### ISSUE THREAD

**Issue by ghost** [raosrinu2004/tachus_bug_tracker#62]
In Main Canvas for Tachus, website mentioned in www.shootontachus.com. This is incorrect and should be replaced by www.tachustechnology.com

**Comment by raosrinu2004** [comment]
share the pics

**Comment by ghost** [comment]
![Capture](https://user-images.githubusercontent.com/47553093/68483319-55a23b00-0261-11ea-92ef-1bd533fa5bef.PNG)

**Comment by ghost** [comment]
Please check at down on right side below tachus logo. Website Mentioned is www.shootontachus.com..This needs to be removed

**Comment by raosrinu2004** [comment]
Its UX based one, will check this next week.

**Comment by raosrinu2004** [comment]
Done some manual modification by myself, if you not liked, do reopen the ticket.
