### ISSUE TITLE
0-Sometimes Scores are not getting detected when we start match 

### ISSUE THREAD

**Issue by ghost** [raosrinu2004/tachus_bug_tracker#67]
Shot not detected: This Issue usually comes at first shot or when we go from sighter to match or we restart match using home button. 

We need a test Application:

1-Hardware connection test should be done at start. 

2-In between match, hardware connection test is not required. 

3-Auto reconnect is not required. 

4-When we go from sighter to match reset is done and 1, 2 and 3 are not required.

5-Inactive home button

**Comment by raosrinu2004** [comment]
Fixed the above issues and shared the binary.
